### PR TITLE
Add Sonatype Lift config file

### PR DESCRIPTION
**Pull request by sleberknight**
* Add .lift.toml to see whether setting to JDK 11 works or not...

### CODE REVIEW

**Comment by TomMD** [comment]
Is there something I can help with or a functionallity you'd like to see?

**Comment by sleberknight** [comment]
@TomMD Sure, thanks for any help! I am just trying to get Lift to work on this little repository to try it out, but it keeps saying "Lift was unable to use your project's build system to produce a compilation database" even though I added a `.lift.toml` file with `build = "maven"` and `jdk11 = true`...

**Comment by sleberknight** [comment]
@TomMD OK, I'm giving up for now. Seems like this is a pretty simple Maven project using JDK 11, but the build logs continue to show that same error "Lift was unable to use your project's build system to produce a compilation database". The project definitely builds cleanly and without errors using Maven, so not sure what I have done wrong, or if there is something I missed in the Lift configuration, etc.

**Comment by sleberknight** [comment]
Just saw this in the build output in one of the maven executions:

```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project ansible-vault-experimental: Fatal error compiling: invalid flag: --release 
```

Not sure where the `--release` even came from.

**Comment by sleberknight** [comment]
I am guessing it has to do with the maven-compiler-plugin and the `<release>` tag which is supported on JDK 9 and higher. I am guessing that Lift is maybe getting confused based on this, but definitely not sure...

**Pull request merged**
